version: '3.8'

services:
  web:
    image: ${DOCKERHUB_USERNAME}/mjsec-boj:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
      - certbot_logs:/var/log/letsencrypt
      - static_volume:/staticfiles
      - media_volume:/media

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt

volumes:
  static_volume:
  media_volume:
  certbot_etc:
  certbot_www:
  certbot_logs:

